language: node_js
sudo: required
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
before_install:
# adds deploy_key for pushing to ${REPO}
- openssl aes-256-cbc -K $encrypted_8e579b44016d_key -iv $encrypted_8e579b44016d_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
after_success:
- .travis/after_success.sh
env:
  global:
  - REPO="git@github.com:RedHatInsights/insights-dashboard-build"
